#!/usr/bin/env bash
# Full local preview that mirrors the Vercel production build.
#   http://localhost:3000/            → redirects to /landing-page.html
#   http://localhost:3000/packs       → packs.html
#   http://localhost:3000/play        → Flutter web app
#   http://localhost:3000/room/ABCDE  → Flutter SPA (shared invite links)
#
# Requires: Flutter SDK (the one build.sh clones into _flutter/ is fine), Node.
set -euo pipefail

# 1) Build: reuses build.sh, so whatever ships on Vercel ships here.
# Env: read Supabase vars from .vercel/.env.development.local (vercel pull) OR .env.
if [ -f ".vercel/.env.development.local" ]; then
  set -a; source .vercel/.env.development.local; set +a
elif [ -f ".env" ]; then
  set -a; source .env; set +a
fi

bash build.sh

# 2) Serve: `serve` reads dist/serve.json (generated by build.sh) and
# applies the same redirects/rewrites as vercel.json.
echo ""
echo "==> Starting local preview at http://localhost:3000"
echo "    Ctrl+C to stop."
cd dist
npx --yes serve -l 3000
