// Mocks generated by Mockito 5.4.6 from annotations
// in vota_amici/test/services/game_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:vota_amici/models/player.dart' as _i3;
import 'package:vota_amici/models/question.dart' as _i9;
import 'package:vota_amici/models/room.dart' as _i2;
import 'package:vota_amici/models/round.dart' as _i7;
import 'package:vota_amici/models/vote.dart' as _i8;
import 'package:vota_amici/repositories/game_repository.dart' as _i6;
import 'package:vota_amici/repositories/room_repository.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRoom_0 extends _i1.SmartFake implements _i2.Room {
  _FakeRoom_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlayer_1 extends _i1.SmartFake implements _i3.Player {
  _FakePlayer_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RoomRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoomRepository extends _i1.Mock implements _i4.RoomRepository {
  MockRoomRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Room?> findRoomByCode(String? code) => (super.noSuchMethod(
        Invocation.method(
          #findRoomByCode,
          [code],
        ),
        returnValue: _i5.Future<_i2.Room?>.value(),
      ) as _i5.Future<_i2.Room?>);

  @override
  _i5.Future<_i2.Room?> findRoomById(String? roomId) => (super.noSuchMethod(
        Invocation.method(
          #findRoomById,
          [roomId],
        ),
        returnValue: _i5.Future<_i2.Room?>.value(),
      ) as _i5.Future<_i2.Room?>);

  @override
  _i5.Stream<_i2.Room?> watchRoom(String? roomId) => (super.noSuchMethod(
        Invocation.method(
          #watchRoom,
          [roomId],
        ),
        returnValue: _i5.Stream<_i2.Room?>.empty(),
      ) as _i5.Stream<_i2.Room?>);

  @override
  _i5.Future<_i2.Room> createRoom({
    required String? code,
    required int? timerSeconds,
    required List<String>? modes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRoom,
          [],
          {
            #code: code,
            #timerSeconds: timerSeconds,
            #modes: modes,
          },
        ),
        returnValue: _i5.Future<_i2.Room>.value(_FakeRoom_0(
          this,
          Invocation.method(
            #createRoom,
            [],
            {
              #code: code,
              #timerSeconds: timerSeconds,
              #modes: modes,
            },
          ),
        )),
      ) as _i5.Future<_i2.Room>);

  @override
  _i5.Future<void> setHost(
    String? roomId,
    String? playerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHost,
          [
            roomId,
            playerId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateRoomStatus(
    String? roomId, {
    _i2.RoomStatus? status,
    int? currentRound,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRoomStatus,
          [roomId],
          {
            #status: status,
            #currentRound: currentRound,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<List<_i3.Player>> watchPlayers(String? roomId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchPlayers,
          [roomId],
        ),
        returnValue: _i5.Stream<List<_i3.Player>>.empty(),
      ) as _i5.Stream<List<_i3.Player>>);

  @override
  _i5.Future<_i3.Player?> findPlayerById(String? playerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findPlayerById,
          [playerId],
        ),
        returnValue: _i5.Future<_i3.Player?>.value(),
      ) as _i5.Future<_i3.Player?>);

  @override
  _i5.Future<_i3.Player?> findPlayerByName({
    required String? roomId,
    required String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findPlayerByName,
          [],
          {
            #roomId: roomId,
            #name: name,
          },
        ),
        returnValue: _i5.Future<_i3.Player?>.value(),
      ) as _i5.Future<_i3.Player?>);

  @override
  _i5.Future<_i3.Player?> findPlayerByRoomAndBrowser({
    required String? roomId,
    required String? browserId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findPlayerByRoomAndBrowser,
          [],
          {
            #roomId: roomId,
            #browserId: browserId,
          },
        ),
        returnValue: _i5.Future<_i3.Player?>.value(),
      ) as _i5.Future<_i3.Player?>);

  @override
  _i5.Future<_i3.Player> createPlayer({
    required String? roomId,
    required String? name,
    bool? isHost = false,
    String? browserId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPlayer,
          [],
          {
            #roomId: roomId,
            #name: name,
            #isHost: isHost,
            #browserId: browserId,
          },
        ),
        returnValue: _i5.Future<_i3.Player>.value(_FakePlayer_1(
          this,
          Invocation.method(
            #createPlayer,
            [],
            {
              #roomId: roomId,
              #name: name,
              #isHost: isHost,
              #browserId: browserId,
            },
          ),
        )),
      ) as _i5.Future<_i3.Player>);
}

/// A class which mocks [GameRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameRepository extends _i1.Mock implements _i6.GameRepository {
  MockGameRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i7.Round>> watchRounds(String? roomId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchRounds,
          [roomId],
        ),
        returnValue: _i5.Stream<List<_i7.Round>>.empty(),
      ) as _i5.Stream<List<_i7.Round>>);

  @override
  _i5.Future<List<_i7.Round>> fetchRoundsForRoom(String? roomId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchRoundsForRoom,
          [roomId],
        ),
        returnValue: _i5.Future<List<_i7.Round>>.value(<_i7.Round>[]),
      ) as _i5.Future<List<_i7.Round>>);

  @override
  _i5.Future<void> startGameRpc({
    required String? roomId,
    required String? firstQuestionId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startGameRpc,
          [],
          {
            #roomId: roomId,
            #firstQuestionId: firstQuestionId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> advanceRoundRpc({
    required String? roomId,
    required String? nextQuestionId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #advanceRoundRpc,
          [],
          {
            #roomId: roomId,
            #nextQuestionId: nextQuestionId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> revealResultsRpc({
    required String? roomId,
    required String? roundId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #revealResultsRpc,
          [],
          {
            #roomId: roomId,
            #roundId: roundId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<List<_i8.Vote>> watchVotesForRound(String? roundId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchVotesForRound,
          [roundId],
        ),
        returnValue: _i5.Stream<List<_i8.Vote>>.empty(),
      ) as _i5.Stream<List<_i8.Vote>>);

  @override
  _i5.Future<List<_i8.Vote>> fetchAllVotes(List<String>? roundIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAllVotes,
          [roundIds],
        ),
        returnValue: _i5.Future<List<_i8.Vote>>.value(<_i8.Vote>[]),
      ) as _i5.Future<List<_i8.Vote>>);

  @override
  _i5.Future<void> submitVote({
    required String? roundId,
    required String? voterId,
    required String? votedForId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitVote,
          [],
          {
            #roundId: roundId,
            #voterId: voterId,
            #votedForId: votedForId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i9.Question>> fetchQuestionsForPack(String? packId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchQuestionsForPack,
          [packId],
        ),
        returnValue: _i5.Future<List<_i9.Question>>.value(<_i9.Question>[]),
      ) as _i5.Future<List<_i9.Question>>);
}
